<a href="https://colab.research.google.com/github/Arjunmukundann/Arjunmukundann-Titanic_Survival_prediction/blob/main/Titanic_Survival_Prediction_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Library

In [97]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#EDA

In [98]:
dataset =pd .read_csv('train.csv')
dataset1=pd.read_csv('gender_submission.csv')
dataset2=pd.read_csv('test.csv')
print('dataset head ',dataset.head())
print('information',dataset.info())
print('describe',dataset.describe())


dataset head     PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN

# Data Cleaning

In [99]:
dataset.drop(['Ticket'],axis=1,inplace=True)
dataset.drop(['PassengerId'],axis=1,inplace=True)
dataset.drop(['Cabin'],axis=1,inplace=True)
dataset.drop(['Name'],axis=1,inplace=True)

In [100]:
print(dataset.isnull().sum())

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64


In [101]:
dataset['Age'].fillna(dataset['Age'].median(),inplace=True)

<ipython-input-101-f17e20bbf39c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Age'].fillna(dataset['Age'].median(),inplace=True)


In [102]:
dataset['Embarked'].fillna(dataset['Embarked'].mode()[0],inplace=True)

<ipython-input-102-34bfef6ea9cc>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Embarked'].fillna(dataset['Embarked'].mode()[0],inplace=True)


In [103]:
dataset['Fare'].fillna(dataset['Fare'].median(),inplace=True)

<ipython-input-103-efe165c4902e>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Fare'].fillna(dataset['Fare'].median(),inplace=True)


In [104]:
print(dataset.isnull().sum())

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64


# Encoded Categorical Variables:

In [105]:
print(dataset.head())

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S


In [106]:
dataset['Embarked']=dataset['Embarked'].map({'C':0,'Q':1,'S':2})
dataset['Sex']=dataset['Sex'].map({'male': 0,'female':1})

In [107]:
print(dataset.head())

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    0  22.0      1      0   7.2500         2
1         1       1    1  38.0      1      0  71.2833         0
2         1       3    1  26.0      0      0   7.9250         2
3         1       1    1  35.0      1      0  53.1000         2
4         0       3    0  35.0      0      0   8.0500         2


# splitting The  Dataset

In [108]:
x=dataset.drop(['Survived'],axis=1)
y=dataset['Survived']

In [109]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

# Feature Scaling

In [110]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
dataset=scaler.fit_transform(dataset)



# Model building

In [111]:
from sklearn.linear_model import LogisticRegression
model2 = LogisticRegression()
model2.fit(x_train, y_train)

LogisticRegression()

In [112]:
from sklearn.ensemble import RandomForestClassifier
model3=RandomForestClassifier(n_estimators=50,max_depth=10,min_samples_leaf=1,min_samples_split=10,criterion='gini',random_state=0,class_weight='balanced')
model3.fit(x_train,y_train)


RandomForestClassifier(class_weight='balanced', max_depth=10,
                       min_samples_split=10, n_estimators=50, random_state=0)

In [113]:
from sklearn.neighbors import KNeighborsClassifier
model4=KNeighborsClassifier(n_neighbors=5)
model4.fit(x_train,y_train)

KNeighborsClassifier()

In [114]:
from sklearn.svm import SVC
model5=SVC(kernel='rbf',random_state=0,C=100,gamma='scale')
model5.fit(x_train,y_train)


SVC(C=100, random_state=0)

In [115]:
from sklearn.tree import DecisionTreeClassifier
model6=DecisionTreeClassifier(criterion='gini',max_depth=10,random_state=0)
model6.fit(x_train,y_train)


DecisionTreeClassifier(max_depth=10, random_state=0)

In [116]:
from sklearn.ensemble import GradientBoostingClassifier
model1=GradientBoostingClassifier(learning_rate= 0.01, max_depth= 3, min_samples_split= 2, n_estimators= 50, random_state=0,subsample= 0.8)
model1.fit(x_train,y_train)
#


GradientBoostingClassifier(learning_rate=0.01, n_estimators=50, random_state=0,
                           subsample=0.8)

# classification report


In [117]:
from sklearn.metrics  import accuracy_score,classification_report,confusion_matrix
models={
    model1:'GradientBoostingClassifier',
    model2:'LogisticRegression',
    model3:'RandomForestClassifier',
    model4:'KNeighborsClassifier',
    model5:'SVC',
    model6:'DecisionTreeClassifier'
}
for model, model_name in models.items():
    y_pred = model.predict(x_test)
    print(f"Model: {model_name}")
    print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print("-" * 50)

Model: GradientBoostingClassifier
Accuracy: 0.8156424581005587
              precision    recall  f1-score   support

           0       0.79      0.96      0.87       110
           1       0.91      0.58      0.71        69

    accuracy                           0.82       179
   macro avg       0.85      0.77      0.79       179
weighted avg       0.83      0.82      0.80       179

[[106   4]
 [ 29  40]]
--------------------------------------------------
Model: LogisticRegression
Accuracy: 0.7988826815642458
              precision    recall  f1-score   support

           0       0.84      0.84      0.84       110
           1       0.74      0.74      0.74        69

    accuracy                           0.80       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179

[[92 18]
 [18 51]]
--------------------------------------------------
Model: RandomForestClassifier
Accuracy: 0.8547486033519553
              precision  

# Data Preprocessing

In [118]:
x_test = dataset2.drop(columns=["PassengerId", "Name", "Cabin", "Ticket"], axis=1)

x_test["Age"] = x_test["Age"].fillna(x_test["Age"].mean())
x_test["Fare"] = x_test["Fare"].fillna(x_test["Fare"].mean())

x_test.isnull().sum()

from sklearn.preprocessing import LabelEncoder

cols = ["Sex", "Embarked"]
le = LabelEncoder()

for col in cols:
    x_test[col] = le.fit_transform(x_test[col])

x_test.head()
x_test

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0         3    1  34.50000      0      0    7.8292         1
1         3    0  47.00000      1      0    7.0000         2
2         2    1  62.00000      0      0    9.6875         1
3         3    1  27.00000      0      0    8.6625         2
4         3    0  22.00000      1      1   12.2875         2
..      ...  ...       ...    ...    ...       ...       ...
413       3    1  30.27259      0      0    8.0500         2
414       1    0  39.00000      0      0  108.9000         0
415       3    1  38.50000      0      0    7.2500         2
416       3    1  30.27259      0      0    8.0500         2
417       3    1  30.27259      1      1   22.3583         0

[418 rows x 7 columns]

# Model Testing

In [119]:
pred = model.predict(x_test)
pred

array([0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,

# Test Submission

In [120]:
submit=pd.read_csv('gender_submission.csv')
submit

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [121]:
submit['Survived']=pred
submit


PassengerId  Survived
0            892         0
1            893         0
2            894         1
3            895         1
4            896         0
..           ...       ...
413         1305         0
414         1306         0
415         1307         0
416         1308         0
417         1309         1

[418 rows x 2 columns]

In [122]:
submit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
dtypes: int64(2)
memory usage: 6.7 KB
